Vagrant.configure("2") do |config|
    config.vm.box="dreamcloud/ubuntu20"
    config.ssh.insert_key = false
    config.vm.box_check_update = false
    
    config.vm.define "ubuntu20" do |ub20|
        ub20.vm.hostname = "ubuntu20"
        ub20.vm.network :private_network, ip: "192.168.99.30"

        ub20.vm.provider :virtualbox do |vb|
            vb.customize ["modifyvm", :id, "--natdnshostresolver1", "off"]
            vb.name="ubuntu20"
            vb.memory=1024
        end
    end
end
