Vagrant.configure("2") do |config|
    config.vm.box="dreamcloud/ubuntu18"
    config.vm.box_version = "2020.09.03"
    config.ssh.insert_key = false
    config.vm.box_check_update = false
    
    config.vm.define "ubuntu18" do |ub18|
        ub18.vm.hostname = "ubuntu18"
        ub18.vm.network :private_network, ip: "192.168.20.10"

        ub18.vm.provider :virtualbox do |vb|
            vb.customize ["modifyvm", :id, "--natdnshostresolver1", "off"]
            vb.name="ubuntu18"
            vb.memory=1024
        end
    end
end
