Vagrant.configure("2") do |config|
    config.vm.box="dreamcloud/centos8"
    config.ssh.insert_key = false
    config.vm.box_check_update = false
    
    config.vm.define "centos8" do |ct8|
        ct8.vm.hostname = "centos8"
        ct8.vm.network :private_network, ip: "192.168.99.20"

        ct8.vm.provider :virtualbox do |vb|
            vb.customize ["modifyvm", :id, "--natdnshostresolver1", "off"]
            vb.name="centos8"
            vb.memory=1024
        end
    end
end
